version: 2.1

jobs:
  installation:
    - image: node:lts
    steps:
      - checkout
      - run: npm ci
  test:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run: docker build -t . mathiz11/node-web-app:snapshot
      - run: docker run -p 8080:8080 -d mathiz11/node-web-app:snapshot
      - run: curl -i http://localhost:8080
  publication:
    docker:
      auth:
        username: $DOCKERHUB_USERNAME
        password: $DOCKERHUB_PASSWORD
      steps:
        - checkout
        - run: docker push mathiz11/node-web-app:0.1
    
    
workflows:
  say-hello-workflow:
    jobs:
      - app
