version: 2.1

jobs:
  installation:
    docker:
      - image: node:lts
    steps:
      - checkout
      - run: npm ci
  test:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run: docker build . -t mathiz11/node-web-app:snapshot
      - run: docker run -p 8080:8080 -d mathiz11/node-web-app:snapshot
      - run: curl -i http://localhost:8080
  publication:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run: docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
      - run : docker build . -t mathiz11/node-web-app
      - run: docker push mathiz11/node-web-app
    
workflows:
  main-workflow:
    jobs:
      - installation
      - test:
          requires:
            - installation
      - publication:
          requires:
            - test
